### ISSUE TITLE
Support Red Hat 8

### ISSUE THREAD

**Issue by iainhallam** [treydock/puppet-yum_cron#21]
Now that RHEL 8 is out, it would be useful if we could manage yum-cron with this module.

**Comment by treydock** [comment]
I haven't deployed RHEL 8 yet so not sure what yum-cron looks like on that OS. Also this module utilizes CentOS docker containers for testing and CentOS hasn't produced 8 yet. If the RHEL 7 values in params.pp can be used for RHEL 8 then could initially just update params.pp and worry about testing once CentOS produces CentOS 8 containers.

**Comment by jadestorm** [comment]
yum-cron isn't a thing anymore in RHEL 8 since they switch to dnf (yum 4).  Most of the yum commands exist as aliases to dnf counterparts -- but yum-cron is replaced with dnf-automatic, which has a similar (if not identical, I'm not sure yet) configuration.  I've considered sending in a PR to this for dnf-automatic, but I waffle on it daily -- should it be it's own module or not.  Same with the yum module -- should it get dnf support or should dnf be a separate module.  What do you think @treydock?  The main sticking point is that it's "really just yum 4" so it makes the decision awkward.  =D

**Comment by jadestorm** [comment]
There's actually a possibility that this module would work fine with dnf-automatic if passed:

service_name => 'dnf-automatic'
package_name => 'dnf-automatic'
config_path => '/etc/dnf/automatic.conf'

I might check that shortly to see if it works.  =)

**Comment by jadestorm** [comment]
Wellll I didn't realize it was going to instafail by not matching the majrelease.  So disregard passing those options as a quick solution.  None-the-less, I'll fork and try a few things because now I'm curious.

**Comment by treydock** [comment]
Would likely be more involved than those 3 parameters as the main `yum_cron_config` type to modify the INI files has the path hardcoded. I think `config_path` is not actually used anymore. I think supporting dnf-automatic is fine for this module given how similar they sound.

**Comment by jadestorm** [comment]
Ha, quite right.  =)  I'll poke around some more with it and submit a PR when I've gotten things worked out.  There's actually a few other .. interesting.. things that don't quite line up.  For example they've switched to using a systemd based timer rather than a cron job.  If you "just start" dnf-automatic, it actually triggers a run.

Anyway, I'll see what I can do.  Since it's a good deal more complicated I doubt it'll be soon <tm> but we'll see.  =)  I'll submit a PR when I have something to submit!

**Comment by jadestorm** [comment]
Ok!  I ended doing it now anyway.  =P  #26  Please let me know what you think!

**Comment by cfeskens** [comment]
I'm running into a compile error on RHEL8 using the most recent yum_cron module:

Server Error: no parameter named 'variable' (file: /etc/puppetlabs/code/environments/RHEL8/modules/yum_cron/manifests/config.pp, line: 24) on Dnf_automatic_config[yum_cron ERROR_LEVEL] (file: /etc/puppetlabs/code/environments/RHEL8/modules/yum_cron/manifests/config.pp, line:24) on node rhel8test.willamette.edu
